# Compiler to use
CC = g++

# Source file
SRC = ticktaktoe.cpp

# Target binary name
TARGET = ticktaktoe

all: $(TARGET)

$(TARGET):
	$(CC) $(SRC) -o $(TARGET)

run:
	./$(TARGET)

clean:
	rm $(TARGET)
