# Compiler to use
CC = g++

# Source file
SRC = program_transformation.cpp

# Target binary name
TARGET = program_transformation

all: $(TARGET)

$(TARGET):
	$(CC) $(SRC) -o $(TARGET)

run:
	./$(TARGET)

clean:
	rm $(TARGET)
